### ISSUE TITLE
Course chart, unable to see percentages

### ISSUE THREAD

**Issue by GrantKlassy** [Madgrades/madgrades.com#12]
Currently, I don't think it's possible to see the percent of students that received a certain grade on the course bar chart. You can follow the bar over to the y axis, but the number above each bar is the raw number of students and hovering over the bar does nothing. It would be nice to have some way to access the percent of students that got each grade. Thanks.

**Comment by thekeenant** [comment]
Percentages do seem more important than the number, especially when you are performing a comparison. I updated the website with an experimental version that shows both, with the percentage emphasized.
