### ISSUE TITLE
GradeDistribution Chart Left Margin Too Tight on Saved Image

### ISSUE THREAD

**Issue by kmui2** [Madgrades/madgrades.com#8]
When I click on the `Save Image` button, the image that gets downloaded has a left margin to be super tight with the left edge (click on image to see at full scale):

![madgrades-2018-11-13t06_13_41 344z](https://user-images.githubusercontent.com/17896701/48394988-3bc82980-e6db-11e8-93c5-0d8606b5285b.png)

I deduced the issue to the following line of code. By replacing the left margin from `-15` to a larger number (i.e. `5`), there would be a larger left margin which resolves the problem. Also, the top margin could also be increased as well.

https://github.com/Madgrades/madgrades.com/blob/aa977d315c24ee112f8b0c3628cbf38f272e2d20/src/containers/charts/GradeDistributionChart.js#L90

![madgrades-2018-11-13t06_32_18 024z](https://user-images.githubusercontent.com/17896701/48395084-9ceffd00-e6db-11e8-8350-0df46d438ec7.png)

**Comment by thekeenant** [comment]
Good find, I can make that fix soon, or if you want to make a pull request I would be happy to merge the change. 👍
